# -*- coding: utf-8 -*-
"""housepredict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJUi1pnjW90FAskkH4psUQeQggRxXh-V
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df =pd.read_csv('/House Price Prediction Dataset.csv')
print(df.head())
print(df.shape)
print(df.dtypes)
print(df.isnull().sum())

df = df.select_dtypes(include=[np.number])
df=df.dropna()

#Correlation Heatmap Core
corr=df.corr()
np.fill_diagonal(corr.values, 0)
fig, ax = plt.subplots(figsize=(10,8))
im = ax.imshow(corr, cmap='coolwarm', vmin=-1, vmax=1)
plt.colorbar(im)
ax.set_xticks(range(len(corr)))
ax.set_yticks(range(len(corr)))
ax.set_xticklabels(corr.columns,rotation=45,ha='right')
ax.set_yticklabels(corr.columns)

for i in range(len(corr)):
  for j in range(len(corr)):
   ax.text(j, i, f'{corr.iloc[i, j]:.2f}', ha='center', va='center', fontsize=8)

plt.title('Correlation Heatmap')
plt.tight_layout()
plt.show()

#Outlier Removal
def remove_outliers_iqr(data):
    Q1 = data.quantile(0.25)
    Q3 = data.quantile(0.75)
    IQR = Q3 - Q1
    mask=~((data < (Q1 - 1.5 * IQR)) | (data > (Q3 + 1.5 * IQR))).any(axis=1)
    return data[mask]

df_clean = remove_outliers_iqr(df)
print(f"Befor:{len(df)} rows → After: {len(df_clean)} rows")

#Feautres and Target _
target_col='Price'
x=df_clean.drop(columns=[target_col]).values
y=df_clean[target_col].values

#Feautres and Scaling
x_mean=x.mean(axis=0)
x_std=x.std(axis=0)
x_norm=(x-x_mean)/x_std

x_b = np.c_[np.ones(x_norm.shape[0]), x_norm]


theta = np.linalg.pinv(x_b.T @ x_b) @ x_b.T @ y

print("Intercept:", theta[0])
print("Coefficients:", theta[1:])

#Prediction And Evaluations
y_pred=x_b @ theta
ss_res=np.sum((y-y_pred)**2)
ss_tot=np.sum((y-y.mean())**2)
r2=1-ss_res /ss_tot

rmse=np.sqrt(np.mean((y-y_pred)**2))

print(f"R-squared: {r2:.4f}")
print(f"RMSE: {rmse:.2f}")

plt.figure(figsize=(8,6))
plt.scatter(y,y_pred,alpha=0.5, color='teal')
plt.plot([y.min(),y.max()],[y.min(),y.max()],'r--',label='Perfect Fit')
plt.xlabel('Actual Price')
plt.ylabel('Predicted Price')
plt.title('Actual vs Predicted')
plt.legend()
plt.tight_layout()
plt.show()

#Residuals Price
residuals=y_pred
plt.figure(figsize=(8,6))
plt.scatter(y_pred,residuals,alpha=0.5,color='coral')
plt.axhline(0,color='Black',linestyle=':')
plt.xlabel('Predicted Price')
plt.ylabel('Residuals')
plt.title('Residuals Plot')
plt.tight_layout()
plt.show()

